name = "toolgenie"
compatibility_date = "2026-10-03"

[assets]
directory = "./dist"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"

[[assets.redirects]]
from = "/terms/"
to = "/terms-of-use/"
status = 301

[[assets.redirects]]
from = "/terms"
to = "/terms-of-use/"
status = 301

[[assets.redirects]]
from = "/index.html"
to = "/"
status = 301
